INSERT INTO tb_cliente (cpf, nome, categoria, data_Nascimento, estado, cidade, rua, numero, logradouro) VALUES ('111', 'Raphael', 'Premium', TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z', 'SP', 'São Paulo', 'Rua 1', '100', 'Centro');
INSERT INTO tb_cliente (cpf, nome, categoria, data_Nascimento, estado, cidade, rua, numero, logradouro) VALUES ('222', 'Jorge', 'Super', TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'RJ', 'Rio de Janeiro', 'Rua 2', '102A', 'Centro');
INSERT INTO tb_cliente (cpf, nome, categoria, data_Nascimento, estado, cidade, rua, numero, logradouro) VALUES ('333', 'Ana', 'Premium', TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'SP', 'São Paulo', 'Rua 1', '100', 'Centro');
INSERT INTO tb_cliente (cpf, nome, categoria, data_Nascimento, estado, cidade, rua, numero, logradouro) VALUES ('444', 'Pedro', 'Premium', TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'MG', 'Belo Horizonte', 'Rua 2', '111', 'Centro');
INSERT INTO tb_cliente (cpf, nome, categoria, data_Nascimento, estado, cidade, rua, numero, logradouro) VALUES ('555', 'Ana Cecilia', 'Super', TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'RJ', 'Rio de Janeiro', 'Rua 10', '102B', 'Centro');
INSERT INTO tb_cliente (cpf, nome, categoria, data_Nascimento, estado, cidade, rua, numero, logradouro) VALUES ('666', 'Monica', 'Super', TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'SP', 'São Paulo', 'Rua 3', '89B', 'Bairro A');
INSERT INTO tb_cliente (cpf, nome, categoria, data_Nascimento, estado, cidade, rua, numero, logradouro) VALUES ('888', 'Moises', 'Premium', TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'MG', 'Belo Horizonte', 'Rua 20', '001', 'Bairro B');
INSERT INTO tb_cliente (cpf, nome, categoria, data_Nascimento, estado, cidade, rua, numero, logradouro) VALUES ('777', 'Renata', 'Premium', TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'RJ', 'Rio de Janeiro', 'Rua 10', '102B', 'Centro');
INSERT INTO tb_cliente (cpf, nome, categoria, data_Nascimento, estado, cidade, rua, numero, logradouro) VALUES ('999', 'Neto', 'Premium', TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'SP', 'São Paulo', 'Rua 5', '030A', 'Bairro D');
